const grossSalary = 5000;
console.log("Gross Salary:", grossSalary);
const paye = grossSalary * 0.2;
console.log("for the gross of ",grossSalary, "the PAYE is", paye);
const Nhif= 2500;
console.log("the NHIF is", Nhif);
const sha= 500;
console.log("the SHA is", sha);
const totalDeductions = paye + Nhif + sha;
console.log("the total deductions are", totalDeductions);
const netSalary = grossSalary - totalDeductions;
console.log("the net salary is", netSalary);